### ISSUE TITLE
The processing of the input is not according with the documentation

### ISSUE THREAD

**Issue by manuelreis** [mfaruqui/eacl14-cca#2]
In the file "alignVectors.py" 

In line 14 ,  `line = line.strip().lower()` should be `line = line.lower()`, otherwise the statement in the following line will not be able to split the word from the vector.

Something similar appears in line 40 `lang2Word, lang1Word = line.strip().split(" ||| ")`, should be `lang2Word, lang1Word = line.split(" ||| ")`. If you strip the whitespaces, you will not be able to split according to `" ||| "`

I also modified my code to `line.rstrip('\n').split(" ||| ")` to remove the '\n' at the end of each line.

**Comment by mfaruqui** [comment]
Hi, I think you understood the issue. line.strip() doesnt not separate whitespaces from within the line, only at the ends. Right?

**Comment by manuelreis** [comment]
Hi, sorry. Right, my mistake. I had some strange problem with my alignment file.

**Comment by mfaruqui** [comment]
No problem, let me know if you need any help.
